### ISSUE TITLE
Did you use K(3->1) drop method in sub center arcface during training?

### ISSUE THREAD

**Issue by AutumnZ-94** [ChristofHenkel/kaggle-landmark-2021-1st-place#2]
Hi,

Did you use K(3->1) drop method in sub center arcface during training, which train twice and offline remove label noise data.

**Comment by ChristofHenkel** [comment]
No. I used plain sub center arcface as defined here
https://github.com/ChristofHenkel/kaggle-landmark-2021-1st-place/blob/main/models/ch_mdl_dolg_efficientnet.py#L42-L58
